listening_port: 12345
ip_address: "0.0.0.0"
target_server: "receiver"
target_port: 8080
data_transfer: tcp
terminator:
  terminator_message: "TERMINATE"
  terminator_ip: "172.19.0.5" # Insert IP here, NOT hostname