version: '3.8'

services:
  receiver:
    build:
      context: .
      dockerfile: docker/Dockerfile.receiver
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/app/scripts
    environment:
      - USE_HTTP=false  # Set to 'true' to use HTTP, 'false' to use TCP

  whisper:
    build:
      context: .
      dockerfile: docker/Dockerfile.whisper
    ports:
      - "12345:12345"
    volumes:
      - ./src:/app/src
      - ./config.yml:/app/config.yml
    environment:
      - CONFIG_PATH=/app/config.yml
    depends_on:
      - receiver

  sender:
    build:
      context: .
      dockerfile: docker/Dockerfile.sender
    volumes:
      - ./scripts:/app/scripts
    environment:
      - WHISPER_HOST=whisper
      - WHISPER_PORT=12345
    depends_on:
      - whisper