# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 
RUN pip install pytest pytest-html pytest-cov

COPY . /app

ENV PYTHONPATH=/app


# Run the test suite and generate reports
CMD ["pytest", "--cov=src", "--cov-report=term", "--cov-report=html", "--html=report.html", "--self-contained-html", "tests/unit_testing/"]
