FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 
RUN pip install pytest pytest-html pytest-cov

COPY . /app

ENV PYTHONPATH=/app


CMD ["pytest", "--cov=src", "--cov-report=term", "--cov-report=html", "--html=report.html", "--self-contained-html", "tests/unit_testing/"]
