FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src
COPY config.yml /app/config.yml

EXPOSE 12345

CMD ["python", "-m", "src.server", "--config", "/app/config.yml"]