FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app/src

EXPOSE 12345

CMD ["python", "-m", "src.server", "--config", "/app/config.yml"]