name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
      with:
        src: "."
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Auto-format code with Black'
        committer_name: GitHub Actions
        committer_email: actions@github.com