name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image for testing
        run: docker build -f docker/Dockerfile.whisper_test -t whisper-test .

      - name: Run tests inside Docker
        run: docker run --rm whisper-test